# Server Configuration
server:
  port: 8081  # Port on which the server will run

# Spring Data Source Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productDB  # Database URL
    username: root  # Database username
    password: 1997  # Database password

  # JPA (Java Persistence API) Configuration
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect  # Database platform, MySQL 8 dialect
    hibernate:
      ddl-auto: update  # Automatic schema update mode

  # Application Name
  application:
    name: PRODUCT-SERVICE  # Name of the Spring Boot application
